/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utilitarios.Conexao;
import Utilitarios.FundoTela;
import java.awt.Frame;
import java.awt.GridLayout;
import java.io.InputStream;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author hugov
 */
public class Principal extends javax.swing.JFrame {

    FundoTela tela;
    ClienteTela clientetela;
    FuncionarioTela functela;
    EntregadorTela enttela;
    CardapioTela cardtela;
    PedidoTela pedtela;
    TelaPedidos telapedidos;
    Connection conexao = null;
    
    public Principal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLayout(new GridLayout());
        tela = new FundoTela("/Icones/pizza-fundo.jpg");
        getContentPane().add(tela);
        
        menu_cliente.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_clientes.png")));
        menuFuncionarios.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_func.png")));
        menuCardapio.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_cardapio.png")));
        menuEntregador.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_boy.png")));
        MenuCadastro.setIcon(new ImageIcon(getClass().getResource("/Icones/inserir-32.png")));
        MenuCaixa.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_caixa.png")));
        MenuRel.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_rel.png")));
        MenuSair.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_sair.png")));
        
        menuPedido.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_pedidos.png")));
         MenuTelaPedidos.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_tela.png")));
        
         menu_tela.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_tela.png")));
        
       ImageIcon icone = new ImageIcon(getClass().getResource("/Icones/ico_cardapio.png"));
       setIconImage(icone.getImage());
       
       
       conexao = Conexao.getConnection();
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        menu_cliente = new javax.swing.JMenuItem();
        menuFuncionarios = new javax.swing.JMenuItem();
        menuCardapio = new javax.swing.JMenuItem();
        menuEntregador = new javax.swing.JMenuItem();
        MenuCaixa = new javax.swing.JMenu();
        menuPedido = new javax.swing.JMenuItem();
        MenuRel = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuTelaPedidos = new javax.swing.JMenu();
        menu_tela = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria Freitas");

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu_cliente.setText("Clientes");
        menu_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(menu_cliente);

        menuFuncionarios.setText("Funcionários");
        menuFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuFuncionarios);

        menuCardapio.setText("Cardápio");
        menuCardapio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCardapioActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuCardapio);

        menuEntregador.setText("Entregador");
        menuEntregador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntregadorActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuEntregador);

        jMenuBar1.add(MenuCadastro);

        MenuCaixa.setText("Caixa");
        MenuCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuPedido.setText("Pedido");
        menuPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoActionPerformed(evt);
            }
        });
        MenuCaixa.add(menuPedido);

        jMenuBar1.add(MenuCaixa);

        MenuRel.setText("Relatórios");
        MenuRel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuRel.add(jMenuItem1);

        jMenuItem2.setText("Pedidos");
        MenuRel.add(jMenuItem2);

        jMenuBar1.add(MenuRel);

        MenuTelaPedidos.setText("Tela Pedidos");
        MenuTelaPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuTelaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTelaPedidosActionPerformed(evt);
            }
        });

        menu_tela.setText("Tela");
        menu_tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_telaActionPerformed(evt);
            }
        });
        MenuTelaPedidos.add(menu_tela);

        jMenuBar1.add(MenuTelaPedidos);

        MenuSair.setText("Sair");
        MenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuSair.add(jMenuItem3);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clienteActionPerformed
       clientetela = new ClienteTela();
       tela.add(clientetela);
       clientetela.setVisible(true);
    }//GEN-LAST:event_menu_clienteActionPerformed

    private void menuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosActionPerformed
        functela = new FuncionarioTela();
       tela.add(functela);
       functela.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosActionPerformed

    private void menuEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntregadorActionPerformed
       enttela = new EntregadorTela();
       tela.add(enttela);
       enttela.setVisible(true);
    }//GEN-LAST:event_menuEntregadorActionPerformed

    private void menuCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCardapioActionPerformed
       cardtela = new CardapioTela();
       tela.add(cardtela);
       cardtela.setVisible(true);
    }//GEN-LAST:event_menuCardapioActionPerformed

    private void menuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoActionPerformed
       pedtela = new PedidoTela(1);
       tela.add(pedtela);
      pedtela.setVisible(true);
    }//GEN-LAST:event_menuPedidoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            
            //Caminho Local - Arquivos não vão junto ao .Jar
            //JasperPrint print = JasperFillManager.fillReport("rel/rel_clientes.jasper", null, conexao );
            
             //Caminho do Pacote - Arquivos  vão junto ao .Jar (forma correta)
             InputStream caminho = getClass().getResourceAsStream("/rel/rel_clientes.jasper");
            JasperPrint print = JasperFillManager.fillReport(caminho, null, conexao );
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuTelaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTelaPedidosActionPerformed
       
    }//GEN-LAST:event_MenuTelaPedidosActionPerformed

    private void menu_telaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_telaActionPerformed
       telapedidos = new TelaPedidos();
       this.setVisible(true);
       telapedidos.setVisible(true);
       
    }//GEN-LAST:event_menu_telaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuCaixa;
    private javax.swing.JMenu MenuRel;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuTelaPedidos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuCardapio;
    private javax.swing.JMenuItem menuEntregador;
    private javax.swing.JMenuItem menuFuncionarios;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menu_cliente;
    private javax.swing.JMenuItem menu_tela;
    // End of variables declaration//GEN-END:variables
}
